"""iRMS 数据模型（Python 与 TS 两版的共同契约）。"""

from irms.models.review import CheckResult, ReviewReport
from irms.models.rules import Rule, RuleConfig, StateMachine, Transition
from irms.models.scenario import (
    Assumption,
    BasicInfo,
    BatteryPolicy,
    CancellationPolicy,
    DispatchConstraint,
    ExceptionBranch,
    Location,
    ManualConfirmation,
    PriorityPolicy,
    Resource,
    RobotType,
    ScenarioModel,
    TaskFlow,
    TaskType,
    Workstation,
    scenario_json_schema,
)
from irms.models.state_machine import (
    Action,
    Guard,
    State,
    StateMachine as TaskStateMachine,
    StateType,
    Transition as StateTransition,
    TransitionType,
    TriggerType,
    state_machine_json_schema,
)
from irms.models.trace import ExecutionTrace, TraceStep

__all__ = [
    "ScenarioModel",
    "BasicInfo",
    "RobotType",
    "TaskType",
    "Workstation",
    "Location",
    "Resource",
    "TaskFlow",
    "DispatchConstraint",
    "BatteryPolicy",
    "PriorityPolicy",
    "CancellationPolicy",
    "ExceptionBranch",
    "Assumption",
    "ManualConfirmation",
    "scenario_json_schema",
    "Action",
    "Guard",
    "State",
    "TaskStateMachine",
    "StateTransition",
    "StateType",
    "TransitionType",
    "TriggerType",
    "state_machine_json_schema",
    "RuleConfig",
    "StateMachine",
    "Transition",
    "Rule",
    "ReviewReport",
    "CheckResult",
    "ExecutionTrace",
    "TraceStep",
]
